// <auto-generated />
namespace Jobs4Developers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class setMigrationByBilel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMigrationByBilel));
        
        string IMigrationMetadata.Id
        {
            get { return "201508081601019_setMigrationByBilel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
